<?php
/**
 * Created by PhpStorm.
 * User: Anderson
 * Date: 05/12/2015
 * Time: 01:25
 */

function headertype(){
    ?>
    <!DOCTYPE html>
    <html><head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <title>Pax boletin</title>
        <meta charset="utf-8">
        <meta generator="csscreator.com">
        <!--[if IE]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script type="text/javascript">
            //<![CDATA[
            try{if (!window.CloudFlare) {var CloudFlare=[{verbose:0,p:0,byc:0,owlid:"cf",bag2:1,mirage2:0,oracle:0,paths:{cloudflare:"/cdn-cgi/nexp/dok3v=1613a3a185/"},atok:"72446ce6db1d95ae03ea03533aaedecd",petok:"d9ebdd0bf2176aa31f34f54481d574d73ad2ad0f-1449288728-1800",zone:"csscreator.com",rocket:"a",apps:{},sha2test:0}];document.write('<script type="text/javascript" src="//ajax.cloudflare.com/cdn-cgi/nexp/dok3v=38857570ac/cloudflare.min.js"><'+'\/script>');}}catch(e){};
            //]]>
        </script><script type="text/javascript" src="style/cloudflare.js"></script><style type="text/css">.cf-hidden { display: none; } .cf-invisible { visibility: hidden; }</style><script data-module="cloudflare/rocket" id="cfjs_block_fdeda7298" onload="CloudFlare.__cfjs_block_fdeda7298_load()" onerror="CloudFlare.__cfjs_block_fdeda7298_error()" onreadystatechange="CloudFlare.__cfjs_block_fdeda7298_readystatechange()" type="text/javascript" src="style/rocket.js"></script>
        <link rel="stylesheet" href="style/style.css" type="text/css">
    </head>
    <body>
    <div id="pagewidth">
        <div id="wrapper" class="clearfix">
            <div id="maincol">
            <div style="display: block; padding: 5px; text-align: center; background-color: black; color: aliceblue; font-family: verdana; font-size: 34px;">Pax Boletim</div>
<?php
}

function footer(){
?>
        </div></div>

        <div style="text-align: center; display: block; margin-bottom: 0px; "> <p>Pax - Boletim online</p><p>Todos os direitos resevados</p></div>

        </body></html>

        <?php
        }
        ?>

